---
title: "Portafolio-edad-moderna"
format: pdf
bibliography: biblio.bib
csl: apa.csl
author:
  - name: JJ Merelo
    email: jjmerelo@correo.ugr.es
    affiliations:
      - name: 2º A Historia del Arte de la Edad Moderna en España
---

# Portafolio de Historia del Arte de la Edad Moderna en España

En las tres etapas trabajaré con un solo edificio o monumento, que ya de por sí es obra arquitectónica, que incluya a su vez esculturas y pinturas. Este edificio es interesante primero por lo improbable de su localización, "porque pudo y porque quiso", en medio de La Mancha, y segundo por la importación de artistas italianos que crearon una obra con poca relación con el entorno y una influencia arquitectónica y artística considerable.

## Palacio del Marqués de Santa Cruz en el Viso del Marqués


### Arquitectura del palacio del Marqués de Santa Cruz

En este apartado nos referiremos al edificio en sí.

#### Autor


#### Cronología
#### Tipología:
#### Análisis descriptivo
#### Contexto histórico-cultural


#### Autor
#### Cronología
#### Tipología:
#### Análisis descriptivo
#### Contexto histórico-cultural

#### Autor
#### Cronología
#### Tipología:
#### Análisis descriptivo
#### Contexto histórico-cultural

#### Autor
#### Cronología
#### Tipología:
#### Análisis descriptivo
#### Contexto histórico-cultural

#### Autor
#### Cronología
#### Tipología:
#### Análisis descriptivo
#### Contexto histórico-cultural

#### Autor
#### Cronología
#### Tipología:
#### Análisis descriptivo
#### Contexto histórico-cultural

#### Autor
#### Cronología
#### Tipología:
#### Análisis descriptivo
#### Contexto histórico-cultural

#### Autor
#### Cronología
#### Tipología:
#### Análisis descriptivo
#### Contexto histórico-cultural

#### Autor
#### Cronología
#### Tipología:
#### Análisis descriptivo
#### Contexto histórico-cultural

## Créditos de las imágenes

Todas las imágenes son del autor, con licencia cc-by-sa, salvo los casos que se comentan a continuación.
